name: example2
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  faker: ^2.1.0
  flutter:
    sdk: flutter
  flutter_fancy_tree_view: ^1.4.1
  flutter_riverpod: ^3.0.0
  my_settings_ui:
    path: ../
  mylib01:
    git:
      url: https://github.com/krijk/mylib01.git

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

